# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: left_joint
  pid: {p: 2000.0, i: 100, d: 500.0}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: right_joint
  pid: {p: 50000.0, i: 100, d: 2000.0}
joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: endeffector
  pid: {p: 20000.0, i: 50, d: 1000.0}
joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: armToEnd
  pid: {p: 2000.0, i: 50, d: 200.0}
joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: topToBot
  pid: {p: 700.0, i: 50, d: 70.0}
joint6_position_controller:
  type: effort_controllers/JointPositionController
  joint: shoulderTolittle
  pid: {p: 2000.0, i: 50, d: 200.0}
joint7_position_controller:
  type: effort_controllers/JointPositionController
  joint: botToBase
  pid: {p: 700.0, i: 50, d: 70.0}

