# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: left_joint
  pid: {p: 100.0, i: 1, d: 1.0}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: right_joint
  pid: {p: 100.0, i: 1, d: 1.0}
joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: endeffector
  pid: {p: 100.0, i: 1, d: 1.0}
joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: armToEnd
  pid: {p: 100.0, i: 1, d: 1.0}
joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: topToBot
  pid: {p: 100.0, i: 1, d: 1.0}
joint6_position_controller:
  type: effort_controllers/JointPositionController
  joint: shoulderTolittle
  pid: {p: 100.0, i: 1, d: 1.0}
joint7_position_controller:
  type: effort_controllers/JointPositionController
  joint: botToBase
  pid: {p: 100.0, i: 1, d: 1.0}

